export * from './mainpage/MainPageLayout'
export * from './about/AboutLayout'
export * from './contact/ContactPageLayout' 
export * from './campaing/CampaingPageLayout'
export * from './campaing/CampaingDetailLayout'
export * from './blog/BlogPageLayout'
export * from './blog/BlogDetailLayout'
export * from './product/ProductPageLayout'